### ISSUE TITLE
Documentation/tutorial for regression

### ISSUE THREAD

**Issue by liutiming** [vanderschaarlab/autoprognosis#26]
Hi Bogdan, congrats on this fantastic tool!

As it is early stage, I am not very sure how to implement regression with AutoPrognosis. For example, there is no RegressionStudy analogous to ClassifierStudy.

Would you like to explain a bit more on this? :)

**Comment by bcebere** [comment]
Hello,

Thank you for the feedback!

Regression support isn't included in the current version, but it can be added in the future.

**Comment by bcebere** [comment]
Added support and tutorials in https://github.com/vanderschaarlab/autoprognosis/pull/28
