### ISSUE TITLE
Error in the example of Demonstrator for classifier in NewClassificationAppProto

### ISSUE THREAD

**Issue by jbwoillard** [vanderschaarlab/autoprognosis#37]
Dear bcebere, I try to execute each tutorial in Colab and I have an error message that I can't solve for demonstrator for classification study in the NewclassificationAppProto
`ValidationError: 1 validation error for NewClassificationAppProto
plot_alternatives
  field required (type=value_error.missing)`
Many thanks in advance for your help
jb

**Comment by jbwoillard** [comment]
A line in the function is missing
`"plot_alternatives": [],`

**Comment by bcebere** [comment]
Hello @jbwoillard 

Thank you for reporting this! 
I updated the notebook with the fix, and it should work now.

Let me know if you still encounter problems.

**Comment by jbwoillard** [comment]
Thanks
