### ISSUE TITLE
Saving an autoprognosis model

### ISSUE THREAD

**Issue by jbwoillard** [vanderschaarlab/autoprognosis#38]
Dear bcebere, how do you save an autoprognosis model file ? It seems tha tpickel does not work for that.
Many thanks in advance
jb

**Comment by bcebere** [comment]
Hello @jbwoillard 

You can use the `save_model`/`load_model` methods from the `autoprognosis.utils.serialization` module.
You can find an example [here](https://github.com/vanderschaarlab/autoprognosis/blob/main/tests/plugins/prediction/classifiers/test_clf_serde.py#L56).

Let me know if this isn't working for you.

**Comment by jbwoillard** [comment]
Thanks that is perfect
