### ISSUE TITLE
Parallel optimization

### ISSUE THREAD

**Issue by dpellow** [vanderschaarlab/autoprognosis#43]
Thanks for this tool! I couldn't tell from the documentation, is there a way to parallelize the optimization across multiple CPUs or cluster nodes?

**Comment by bcebere** [comment]
Hello @dpellow ,

Thank you for your question.

We added a few env variables and docs to address this in the latest release.

The variables are

| Variable       | Description                                                     |
|----------------|-----------------------------------------------------------------|
| `N_OPT_JOBS`     | Number of cores to use for hyperparameter search. Default : 1 |
| `N_LEARNER_JOBS` | Number of cores to use by inidividual learners. Default: all cpus      |
| `REDIS_HOST`     | IP address for the Redis database. Default 127.0.0.1            |
| `REDIS_PORT`     | Redis port. Default: 6379                                       |

Using  `N_OPT_JOBS`  and  `N_LEARNER_JOBS` , you can control the parallelism on a single host.

When running in cluster nodes, it is recommended to use the library with a Redis database.  You can specify `REDIS_HOST` and `REDIS_PORT`, and the nodes can use the database to sync the optimization process.

**Comment by dpellow** [comment]
Thanks!
