### ISSUE TITLE
Possibility to perform upsampling

### ISSUE THREAD

**Issue by jbwoillard** [vanderschaarlab/autoprognosis#75]
Dear mainteners, we tested autoprognosis with one of our dataset with class highly imbalanced (event proportion =16%). Autoprognosis returned values of sensitivity to 0 and specificity to 1(classification of all patients as non event). Would it be possible to add an upsampling step in the AutoML solution for these specific case or to change the optimisation metrics?
Thanks in advance 
All the best
jb

**Comment by DrShushen** [comment]
This is not currently planned unfortunately but you can use other open source libraries like `sklearn`, `imblearn` to perform this on your dataset before using autoprognosis
