### ISSUE TITLE
Can Autoprognosis handle collinearity?

### ISSUE THREAD

**Issue by williamty** [vanderschaarlab/autoprognosis#78]
Collinearity is a common problem in medical analysis. For example, age group is classified data, and age is numerical data. If the data is not collinearly processed, it will produce a very high prediction accuracy, but it is meaningless. How will Autoprognosis handle that?

**Comment by DrShushen** [comment]
AutoPrognosis handles multi-collinearity here:
https://github.com/vanderschaarlab/autoprognosis/blob/2b71de4cddb1fc63ed48c1df244e4afcdce802ce/src/autoprognosis/plugins/preprocessors/dimensionality_reduction/plugin_data_cleanup.py
