### ISSUE TITLE
How to use time dependent covariates in the survival analysis?

### ISSUE THREAD

**Issue by 11Dmitriy11** [vanderschaarlab/autoprognosis#81]
## Question
How to use time dependent covariates in the survival analysis?

## Further Information
I am able to perform Cox model with time dependent covariates in R (using tmerge function to preprocess data). Is there any possibility to perform such type of analysis using autoprognosis?

**Comment by DrShushen** [comment]
Please have a look at
https://github.com/vanderschaarlab/temporai
for that use case
