### ISSUE TITLE
Which diff between Study.fit() and Study.run() ？

### ISSUE THREAD

**Issue by zhaoxiongjun** [vanderschaarlab/autoprognosis#83]
## Question
**Which diff between Study.fit() and Study.run() ？**

**Comment by hamed8888** [comment]
run() tries to find the best configuration for the model, ie the best combination of hyperparameters and classifiers,but it does not applies the found configuration to the model. If you need to train the model, maybe to use in your production environment, you need to do it using fit()

**Comment by DrShushen** [comment]
Thanks @hamed8888 for providing the answer!
